### PR TITLE
fix callback typo

### PR DESCRIPTION
**Pull request by cryptix**
pointed out by https://github.com/flumedb/flumeview-level/pull/25#discussion_r435692595
thanks @vweevers!

### CODE REVIEW

**Comment by christianbundy** [comment]
Thanks for fixing this!

**Comment by mixmix** [comment]
oh jeez, this looks like a party!
Nice sharp eyes <3

**Comment by cryptix** [comment]
More then welcome :) 

_someone_ still needs to publish a patch version of this to npm, right?

**Comment by mixmix** [comment]
Christian had access and merged it, so I trust him to have next about when
deploying is right?
Is that the right assumption Christian?

**Pull request merged**
