### PR TITLE
Fix version change destroy

### PR DESCRIPTION
**Pull request by mmckegg**
Looks like changing the version isn't causing the db to deleted. It just causes it to lock up.

This is because the `close` method (that is called by `destroy`) checks to see if the since value exists. But this is not created when the version changes.

**This PR adds a special flag `outdated`, that gets set to true when the version has changed. If `outdated` is `true` then the database is closed immediately.**

cc @dominictarr

### CODE REVIEW

**Comment by mmckegg** [comment]
We need to add a test for this as this isn't the first time this has broken.

**Comment by mmckegg** [comment]
This needs to be merged! A bunch of people have had to nuke their flume indexes manually since `ssb-backlinks` was bumped.

cc @dominictarr

**Comment by cryptix** [comment]
> It just causes it to lock up.

does that mean it just stalls / doesn't continue? I had two reports of this also...

**Comment by mmckegg** [comment]
> does that mean it just stalls / doesn't continue? I had two reports of this also...

Yep, that's exactly what happens!

**Comment by dominictarr** [comment]
merged into 2.1.1

**Pull request merged**
